# Generated by Django 4.2.22 on 2025-06-08 07:10

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePublicToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generate Token',
                'verbose_name_plural': 'Generate Tokens',
            },
        ),
        migrations.CreateModel(
            name='GenerateGroup',
            fields=[
                ('crated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=api.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('public_token', models.UUIDField(default=api.models.generate_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generate Group',
                'verbose_name_plural': 'Generate Groups',
            },
        ),
    ]
