# Generated by Django 4.2.23 on 2025-08-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostfileToLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='library_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='target_library', to='api.generatelibrary')),
            ],
        ),
    ]
