# Generated by Django 4.2.23 on 2025-08-02 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_postfiletolibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiletolibrary',
            name='auther',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auther', to=settings.AUTH_USER_MODEL),
        ),
    ]
