# Generated by Django 4.2.23 on 2025-08-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_postfiletolibrary_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiletolibrary',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
