# Generated by Django 4.2.22 on 2025-06-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customoutstandingtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomOutstandingToken',
        ),
    ]
