# Generated by Django 4.2.23 on 2025-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_postfiletolibrary_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectlibrary',
            unique_together={('group', 'target')},
        ),
        migrations.AddIndex(
            model_name='connectlibrary',
            index=models.Index(fields=['group', 'target'], name='api_connect_group_i_024e0a_idx'),
        ),
    ]
