# Generated by Django 4.2.22 on 2025-06-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_customoutstandingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOutStandingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(unique=True, verbose_name='JTI')),
                ('token', models.TextField(verbose_name='トークン文字列')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アウトスタンディングトークン',
                'verbose_name_plural': 'アウトスタンディングトークン',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomBlackListToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='ブラックリスト登録日時')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_token', to='api.customoutstandingtoken')),
            ],
            options={
                'verbose_name': 'カスタム無効トークン',
                'verbose_name_plural': 'カスタム無効トークン一覧',
                'ordering': ['-blacklisted_at'],
            },
        ),
    ]
