# Generated by Django 4.2.22 on 2025-06-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customoutstandingtoken_customblacklisttoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generategroup',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='generategroup',
            name='public_token',
        ),
        migrations.RemoveField(
            model_name='generategroup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='generategroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='joined_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='requires_secret_key',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatepublictoken',
            name='groups',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='group_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatepublictoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatepublictoken',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generategroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatepublictoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='generatepublictoken',
            unique_together={('user', 'groups')},
        ),
        migrations.RemoveField(
            model_name='generatepublictoken',
            name='expires_at',
        ),
    ]
