# Generated by Django 4.2.23 on 2025-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_connectlibrary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_done',
            field=models.BooleanField(default=False, help_text='このメッセージが完了したか？'),
        ),
    ]
