# Generated by Django 4.2.23 on 2025-08-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(default=0, help_text='投票の値。正の値は賛成、負の値は反対を示す。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='投票対象ゴール', to='api.goal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='投票者', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('goal', 'voter')},
            },
        ),
    ]
