# Generated by Django 4.2.22 on 2025-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_generategroup_founder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avater',
            field=models.URLField(blank=True, null=True),
        ),
    ]
