# Generated by Django 4.2.22 on 2025-06-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepublictoken',
            name='groups',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='group_tokens', to='api.generategroup'),
        ),
    ]
