# Generated by Django 4.2.23 on 2025-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_goalvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalvote',
            name='vote_value',
        ),
        migrations.AddField(
            model_name='goalvote',
            name='is_yes',
            field=models.BooleanField(default=False, help_text='この投票が賛成か？'),
        ),
    ]
