# Generated by Django 4.2.23 on 2025-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_goalvote_vote_value_goalvote_is_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalvote',
            name='explain',
            field=models.CharField(blank=True, help_text='この投票の目的や背景を説明するテキスト', max_length=50, null=True),
        ),
    ]
