# Generated by Django 4.2.22 on 2025-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_generatepublictoken_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='generategroup',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
