# Generated by Django 4.2.23 on 2025-08-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_goalvote_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalvote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ターゲット', to='api.generategroup'),
        ),
    ]
