# Generated by Django 4.2.23 on 2025-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_goalvote_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalvote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='goalvote',
            name='is_yes',
            field=models.BooleanField(),
        ),
        migrations.AddIndex(
            model_name='goalvote',
            index=models.Index(fields=['group', 'goal'], name='api_goalvot_group_i_579181_idx'),
        ),
        migrations.AddIndex(
            model_name='goalvote',
            index=models.Index(fields=['voter'], name='api_goalvot_voter_i_104122_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalvote',
            constraint=models.UniqueConstraint(fields=('goal', 'voter'), name='uniq_goal_voter'),
        ),
    ]
