# Generated by Django 4.2.22 on 2025-06-18 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_generatelibrary_generategroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatelibrary',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
