# Generated by Django 4.2.23 on 2025-06-19 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_generatelibrary_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generategroup',
            options={},
        ),
        migrations.RenameField(
            model_name='generategroup',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='generategroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generategroup',
            name='requires_secret_key',
        ),
        migrations.RemoveField(
            model_name='generategroup',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='generatelibrary',
            name='description',
        ),
        migrations.AddField(
            model_name='generategroup',
            name='generate_credits',
            field=models.IntegerField(default=100, help_text='生成機能を使用するためのクレジット', verbose_name='生成クレジット'),
        ),
        migrations.AddField(
            model_name='generategroup',
            name='score',
            field=models.IntegerField(default=100, help_text='グループの活動状況に基づくスコア。デフォルト:100, 最大:1000', verbose_name='スコア'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='目標内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('deadline', models.DateField(blank=True, help_text='この目標の締め切り', null=True, verbose_name='締め切り')),
                ('is_concrete', models.BooleanField(default=False, help_text='締め切りか担当者が設定されると自動でTrueになります', verbose_name='具体化済み')),
                ('is_completed', models.BooleanField(default=False, verbose_name='達成済み')),
                ('assignee', models.ForeignKey(blank=True, help_text='この目標の責任者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goal', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='目標', to='api.generategroup')),
            ],
        ),
        migrations.AddField(
            model_name='generategroup',
            name='goals',
            field=models.ManyToManyField(blank=True, to='api.goal'),
        ),
    ]
