# Generated by Django 4.2.23 on 2025-08-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_goalvote_unique_together_alter_goalvote_is_yes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteappover',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='inviteappover',
            name='inviter',
        ),
        migrations.DeleteModel(
            name='GeneratePublicToken',
        ),
        migrations.DeleteModel(
            name='InviteAppover',
        ),
    ]
