# Generated by Django 4.2.23 on 2025-08-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_inviteappover_invitee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiletolibrary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
