# Generated by Django 4.2.23 on 2025-06-20 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_generategroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='接続先スタジオ', to='api.generategroup')),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='対象ライブラリ', to='api.generatelibrary')),
            ],
        ),
    ]
