# Generated by Django 4.2.23 on 2025-08-12 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_postfiletolibrary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalvote',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.goal'),
        ),
        migrations.AlterField(
            model_name='goalvote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_group', to='api.generategroup'),
        ),
        migrations.AlterField(
            model_name='goalvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
