# Generated by Django 4.2.23 on 2025-06-22 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_connectlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generategroup',
            name='joined_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
