# Generated by Django 4.2.23 on 2025-08-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_goalvote_goal_alter_goalvote_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectlibrary',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='接続先スタジオ', to='api.generategroup'),
        ),
        migrations.AlterField(
            model_name='connectlibrary',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='対象ライブラリ', to='api.generatelibrary'),
        ),
        migrations.AlterField(
            model_name='generategroup',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generategroup',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='generatelibrary',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatelibrary',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='goal',
            name='header',
            field=models.CharField(blank=True, default=None, help_text='この目標のタイトル', max_length=255, null=True, verbose_name='目標タイトル'),
        ),
        migrations.AlterField(
            model_name='postfiletolibrary',
            name='auther',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auther', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postfiletolibrary',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target_library', to='api.generatelibrary'),
        ),
    ]
