# Generated by Django 4.2.23 on 2025-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_connectlibrary_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='進捗率（0〜100）'),
        ),
    ]
