# Generated by Django 4.2.23 on 2025-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_groupnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generategroup',
            name='joined_token',
            field=models.CharField(blank=True, help_text='UUID形式の招待トークン', max_length=36, null=True, unique=True),
        ),
    ]
