# Generated by Django 4.2.23 on 2025-08-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_goal_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
    ]
