# Generated by Django 4.2.23 on 2025-06-26 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_generategroup_joined_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approver',
            field=models.ManyToManyField(blank=True, related_name='freind_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
