# Generated by Django 4.2.23 on 2025-06-27 08:13

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customuser_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteAppover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=api.models.get_default_expired)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generategroup')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_invite_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'グループ招待トークン',
                'verbose_name_plural': 'グループ招待トークン',
                'ordering': ['-created_at'],
            },
        ),
    ]
