# Generated by Django 4.2.23 on 2025-08-17 12:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_goal_progress'),
        ('api', '0020_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generategroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_group_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='generategroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tag'], name='idx_group_tag_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='generatelibrary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_library_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='generatelibrary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tag'], name='idx_library_tag_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
