# Generated by Django 4.2.23 on 2025-08-17 13:04

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_goal_progress'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
    ]
