# Generated by Django 4.2.23 on 2025-06-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inviteappover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteappover',
            name='group',
        ),
    ]
