# Generated by Django 4.2.23 on 2025-08-20 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_inviteappover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalvote',
            name='is_yes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_yes', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_goalvote', to='api.goalvote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('goal_vote', 'voter'), name='uniq_voter'),
        ),
    ]
