# Generated by Django 4.2.23 on 2025-08-22 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_goalvote_is_yes_vote_vote_uniq_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='goal_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='api.goalvote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL),
        ),
    ]
