# Generated by Django 4.2.23 on 2025-06-28 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_inviteappover_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approver',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
