# Generated by Django 4.2.23 on 2025-08-22 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_vote_goal_vote_alter_vote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='goal_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_goalvote', to='api.goalvote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
