# Generated by Django 4.2.23 on 2025-07-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_customuser_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='header',
            field=models.CharField(default='', help_text='この目標のタイトル', max_length=255, verbose_name='目標タイトル'),
        ),
    ]
