# Generated by Django 4.2.24 on 2025-10-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_vote_goal_vote_alter_vote_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generategroup',
            name='goals',
        ),
        migrations.AlterField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.generategroup'),
        ),
    ]
