# Generated by Django 4.2.23 on 2025-07-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_goal_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='header',
            field=models.CharField(blank=True, default='', help_text='この目標のタイトル', max_length=255, null=True, verbose_name='目標タイトル'),
        ),
    ]
