# Generated by Django 4.2.23 on 2025-07-29 02:42

# from django.db import migrations, models
# import uuid


# class Migration(migrations.Migration):

#     dependencies = [
#         ('api', '0024_alter_goal_header'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='goal',
#             name='id',
#             field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
#         ),
#     ]
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_goal_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='uuid_tmp',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
