# Generated by Django 4.2.23 on 2025-07-29 02:44

from django.db import migrations
import uuid

def assign_uuid(apps, schema_editor):
    Goal = apps.get_model("api", "Goal")
    for goal in Goal.objects.all():
        goal.uuid_tmp = uuid.uuid4()
        goal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_goal_id'),
    ]

    operations = [
        migrations.RunPython(assign_uuid),
    ]
