# Generated by Django 4.2.23 on 2025-07-29 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20250729_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='uuid_tmp',
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
