#!/bin/bash
set -e
# SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# ENV_PATH="$SCRIPT_DIR/../.env.production"
# echo "📦 Loading environment variables from $ENV_PATH..."

# # 手動で読み込む
# set -a
# source "$ENV_PATH"
# set +a

# PYTHON MAGRATE
export DJANGO_SETTINGS_MODULE=config.settings

# PORT=${PORT:-8181}
PORT=${PORT:-8000}
python manage.py migrate --noinput

echo "🛠️ Creating superuser..."
echo "from django.contrib.auth import get_user_model; \
      User = get_user_model(); \
      User.objects.filter(email='takatokomada17@gmail.com').exists() or \
      User.objects.create_superuser('takatokomada17@gmail.com', '20050605')" \
    | python manage.py shell


exec gunicorn config.wsgi:application --preload --bind 0.0.0.0:${PORT} --workers 3 --timeout 120