#!/bin/bash
set -e
export RUN_SUPERUSER=1
echo "🧪 環境変数チェック:"
echo "  RUN_SUPERUSER=$RUN_SUPERUSER"

python manage.py migrate
python manage.py collectstatic --noinput

if [ "$RUN_SUPERUSER" = "1" ]; then
  echo "🛠️ Creating superuser..."
  python manage.py createsuperuser --noinput \
    --email takatokomada17@gmail.com || echo "✅ Superuser already exists."
fi

# アプリ起動
echo "🚀 Starting app: $@"
exec "$@"
