name: Deploy Nuxt to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: "20"

      # （任意）Monorepo や private registry を使うなら .npmrc 設定などをここで

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}   # PR コメント等に使用
          action: "upload"

          # --- パス設定（あなたの構成に合わせてある）---
          app_location: "frontend/xerofront"        # Nuxt プロジェクトの場所
          api_location: ""                          # API がなければ空
          output_location: ".output/public"         # Nuxt generate の出力

          # --- ビルドコマンド ---
          # Nuxt 3 の静的生成（SSG）。package.json に "generate": "nuxt generate" がある前提
          app_build_command: "npm ci && npm run generate"
